config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  
  devise_for :users
  resources :events
  resources :users, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

 belongs_to :user
 belongs_to :event

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :user
  
  validates :start_date, presence: true
  validates :duration, presence: true
  validates :title, presence: true, length: {in: 5..140}
  validates :description, presence: true, length: {in: 20..1000}
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 1001}
  validates :location, presence: true
  
  


  def date(start_date)
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "date not available")
    end
  end

  def time(duration)

    if (duration % 5) != 0
      errors.add(:duration, "duration not available")
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances
  #validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password)}
          end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @event = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params_event)
    @event.user = current_user
    if @event.save!
      redirect_to event_path(@event.id)
      flash[:notice] = "Event was successfully create"

    else render :new
      flash[:alert] = "Error : answer to all questions"
    end

  end

  def params_event
    params.require(:event).permit(:user, :start_date, :duration, :title, :description, :price, :location)
  end

  def show
    @event = Event.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user
  before_action :only_see_own_page, only: [:show]

  def show
    @user = User.find(params[:id])

    @event = Event.all
    
    
  end

  def only_see_own_page
    @user = User.find(params[:id])
  
    if current_user != @user
      redirect_to root_path, notice: "Sorry, but you are only allowed to view your own profile page."
    end
  end
  

  private
  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/new.html.erb
<h6>Create your event</h6>

<%= form_for(@event, method: :post) do |f| %>
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  

  <div class="form-group">
    <%= f.label :title %><br/>
    <%= f.text_field :title, autofocus: true, autocomplete: "Title" %>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_field :description, autofocus: true, autocomplete: "Description" %>
  </div>
  <hr>
   <div class="form-group">
    <%= f.label :start_date %><br />
    <%= f.date_field :start_date, autofocus: true, autocomplete: "Start date" %>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label :duration %><br />
    <%= f.number_field :duration, autofocus: true, autocomplete: "Duration(mn)" %>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label :location %><br />
    <%= f.text_field :location, autofocus: true, autocomplete: "Location" %>
  </div>
  <hr>
  <div class="form-group">
    <%= f.label :price %><br />
    <%= f.number_field :price, autofocus: true, autocomplete: "Price" %>
  </div>
  <hr>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="card mx-auto my-4 shadow" style="width: 50rem;">
  <img class="card-img" src="https://picsum.photos/id/<%= rand(1..99) %>/500/230" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title"> Title : <%= @event.title%> </h5>
    <p class="card-text"><%=@event.description%></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Price : <%=@event.price%></li>
    <li class="list-group-item">Location : <%=@event.location%></li>
    <li class="list-group-item">Auhor : <%= @event.user.first_name%> <%= @event.user.last_name%></li>
  </ul>
  <div class="card-body">
    <a href="#" class="card-link">Card link</a>
    <a href="#" class="card-link">Another link</a>
  </div>
</div>

app/views/home/index.html.erb
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Album example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Main call to action</a>
        
      </p>
    </div>
  </section>
    <div class="row">
    <% @events.each do |e|%>
        <div class="card mx-auto my-4 shadow" style="width: 20rem;">

        <div class="album py-5 bg-light">
          <div class="container">

            <div class="card mb-4 shadow-sm">
            <img class="card-img" src="https://picsum.photos/id/<%= rand(1..99) %>/500/230" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text"><%=e.description%></p>
                    <p class="card-text">The Price :<%= e.price %></p>
                    <p class="card-text">The place to Be :<%= e.location %></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                          <a <%= link_to "Details", event_path(e.id),  :class => "btn btn-primary" %></a>
                        </div>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
    <%end%>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>THPEventbriteDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" <%=link_to "EventBrite",home_index_path %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" <%= link_to "Create event", new_event_path %> <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? %>
      <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              My profile
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="<%=user_path(current_user.id)%>">Profile</a>
              <a class="dropdown-item" href="<%=edit_user_registration_path%>">Edit</a>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"dropdown-item" %>
            </div>
          </div>
        <% else %>
        <div class="btn-group">
            <button type="button" class="btn btn-outline-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Log in / Inscription
            </button>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="<%=new_user_session_path%>">Log in</a>
              <a class="dropdown-item" href="<%=new_user_registration_path%>">Inscription</a>
            </div>
          </div>
        <% end %>
      </li>
    </ul>
  </div>
</nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Profil</h1>


<div class="container">

      

  <div class="row gutters-sm">
    <div class="col-md-4 d-none d-md-block">
      <div class="card">
        <div class="card-body">
          <nav class="nav flex-column nav-pills nav-gap-y-1">
            <a href="#profile" data-toggle="tab" class="nav-item nav-link has-icon nav-link-faded active">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user mr-2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>Profile Information
            </a>
          </nav>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="card">
      <div class="card-header border-bottom mb-3 d-flex d-md-none">
        <ul class="nav nav-tabs card-header-tabs nav-gap-x-1" role="tablist">
          <li class="nav-item">
            <a href="#profile" data-toggle="tab" class="nav-link has-icon active"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg></a>
          </li>
          <li class="nav-item">
            <a href="#account" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-settings"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg></a>
          </li>
          <li class="nav-item">
            <a href="#security" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-shield"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path></svg></a>
          </li>
          <li class="nav-item">
            <a href="#notification" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bell"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg></a>
          </li>
          <li class="nav-item">
            <a href="#billing" data-toggle="tab" class="nav-link has-icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-credit-card"><rect x="1" y="4" width="22" height="16" rx="2" ry="2"></rect><line x1="1" y1="10" x2="23" y2="10"></line></svg></a>
          </li>
        </ul>
      </div>
      <div class="card-body tab-content">
        <div class="tab-pane active" id="profile">
          <h6>YOUR PROFILE INFORMATION</h6>
          <hr>
          <form>
            <div class="form-group">
              <label for="first_name">First Name :</label>
              <%= @user.first_name%>
            </div>
            <div class="form-group">
              <label for="last_name">Last Name :</label>
              <%= @user.last_name%>
            </div>
            <div class="form-group">
              <label for="emai">Email :</label></br>
              <%= @user.email%>
            </div>
          </form>
          <% @event.each do |e|%>
              <% if e.user.id == current_user.id %>
              <p> 
              <a <%= link_to "#{e.title}", event_path(e.id) %></a>
              </p>
              <%end%>
          <%end%>
        </div>  
      </div>
    </div>
  </div>
</div>